version: "3.9"

services:
  model_backend_migrate:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-controller-model
    image: ${MODEL_BACKEND_IMAGE}:latest

  model_backend_init:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-controller-model
    image: ${MODEL_BACKEND_IMAGE}:latest

  model_backend_worker:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-controller-model
    image: ${MODEL_BACKEND_IMAGE}:latest
    environment:
      CFG_SERVER_DEBUG: "true"

  model_backend:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-controller-model
    image: ${MODEL_BACKEND_IMAGE}:latest
    environment:
      CFG_SERVER_DEBUG: "true"
      CFG_SERVER_EDITION: ${EDITION}
    ports:
      - ${MODEL_BACKEND_PRIVATEPORT}:${MODEL_BACKEND_PRIVATEPORT}
      - ${MODEL_BACKEND_PUBLICPORT}:${MODEL_BACKEND_PUBLICPORT}

  model_backend_init_model:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-controller-model
    image: ${MODEL_BACKEND_IMAGE}:latest
    environment:
      CFG_INITMODEL_ENABLED: ${INITMODEL_ENABLED}
      CFG_INITMODEL_PATH: https://raw.githubusercontent.com/instill-ai/model/main/model-hub/model_hub_cpu.json

  controller_model:
    profiles:
      - all
      - exclude-api-gateway
      - exclude-mgmt
      - exclude-console
      - exclude-pipeline
      - exclude-model
    image: ${CONTROLLER_MODEL_IMAGE}:latest
    environment:
      CFG_SERVER_DEBUG: "true"
      CFG_SERVER_EDITION: ${EDITION}
    ports:
      - ${CONTROLLER_MODEL_PRIVATEPORT}:${CONTROLLER_MODEL_PRIVATEPORT}

  ray_server:
    image: ${RAY_SERVER_IMAGE}:${RAY_LATEST_TAG}
    ports:
      - ${RAY_SERVER_CLIENT_PORT}:${RAY_SERVER_CLIENT_PORT}
      - ${RAY_SERVER_DASHBOARD_PORT}:${RAY_SERVER_DASHBOARD_PORT}
      - ${RAY_SERVER_SERVE_PORT}:${RAY_SERVER_SERVE_PORT}
      - ${RAY_SERVER_SERVE_GRPC_PORT}:${RAY_SERVER_SERVE_GRPC_PORT}
      - ${RAY_SERVER_PROMETHEUS_PORT}:${RAY_SERVER_PROMETHEUS_PORT}
