{{- if and .Values.internalTLS.enabled (eq .Values.internalTLS.certSource "auto") }}
{{- $ca := genCA "model-internal-ca" 365 }}
{{- $modelCN := (include "model.modelBackend" .) }}
{{- $modelCrt := genSignedCert $modelCN (list "127.0.0.1") (list "localhost" $modelCN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "model.internalTLS.modelBackend.secretName" . }}"
  labels:
    {{- include "model.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $modelCrt.Cert | b64enc | quote }}
  tls.key: {{ $modelCrt.Key | b64enc | quote }}
{{- end }}
