apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "model.modelBackend" . }}
  labels:
    {{- include "model.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-backend
data:
  config.yaml: |+
    server:
      privateport: {{ template "model.modelBackend.privatePort" . }}
      publicport: {{ template "model.modelBackend.publicPort" . }}
      edition: {{ .Values.edition }}
      usage:
        {{- toYaml .Values.usage | nindent 8 }}
      debug: {{ ternary "true" "false" (eq (.Values.logLevel | upper) "DEBUG") }}
      itmode:
        enabled: {{ .Values.itMode.enabled }}
      maxdatasize: {{ .Values.maxDataSizeMB }}
      workflow:
        maxworkflowtimeout: {{ .Values.modelBackend.temporal.workflow.maxWorkflowTimeout }}
        maxworkflowretry: {{ .Values.modelBackend.temporal.workflow.maxWorkflowRetry }}
        maxactivityretry: {{ .Values.modelBackend.temporal.workflow.maxActivityRetry }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/instill-ai/model/ssl/model/tls.crt
        key: /etc/instill-ai/model/ssl/model/tls.key
      {{- end }}
    log:
      external: {{ .Values.tags.observability }}
      otelcollector:
        host: {{ template "core.otel" . }}
        port: {{ template "core.otel.port" . }}
    mgmtbackend:
      host: {{ template "core.mgmtBackend" . }}
      privateport: {{ template "core.mgmtBackend.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/instill-ai/model/ssl/mgmt/tls.crt
        key: /etc/instill-ai/model/ssl/mgmt/tls.key
      {{- end }}
    controller:
      host: {{ template "model.controllerModel" . }}
      privateport: {{ template "model.controllerModel.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/instill-ai/model/ssl/controller/tls.crt
        key: /etc/instill-ai/model/ssl/controller/tls.key
      {{- end }}
    tritonserver:
      grpcuri: {{ include "model.triton" . }}:{{ include "model.triton.grpcPort" . }}
      modelstore: /model-repository
    rayserver:
      grpcuri: {{ include "model.ray" . }}-raycluster:{{ include "model.ray.serveGrpcPort" . }}
      modelstore: /model-repository
    database:
      username: {{ default (include "core.database.username" .) .Values.database.username }}
      password: {{ default (include "core.database.rawPassword" .) .Values.database.password }}
      host: {{ default (include "core.database.host" .) .Values.database.host }}
      port: {{ default (include "core.database.port" .) .Values.database.port }}
      name: model
      version: {{ .Values.modelBackend.dbVersion }}
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ default (include "core.redis.addr" .) .Values.redis.addr }}
    maxbatchsizelimitation:
      unspecified: 2
      classification: 16
      detection: 8
      keypoint: 8
      ocr: 2
      instancesegmentation: 8
      semanticsegmentation: 8
      textgeneration: 1
    temporal:
      hostport: {{ default (printf "%s-frontend-headless:%s" (include "core.temporal" .) (include "core.temporal.frontend.grpcPort" .)) .Values.modelBackend.temporal.hostPort }}
      namespace: {{ default "model-backend" .Values.modelBackend.temporal.namespace }}
      ca: {{ default "" .Values.modelBackend.temporal.ca }}
      cert: {{ default "" .Values.modelBackend.temporal.cert }}
      key: {{ default "" .Values.modelBackend.temporal.key }}
      serverName: {{ default "" .Values.modelBackend.temporal.serverName }}
    initmodel:
      path: {{ .Values.modelBackend.initModel.path }}
      enabled: {{ .Values.modelBackend.initModel.enabled }}
