apiVersion: v1
kind: Service
metadata:
{{- if or (eq .Values.expose.type "clusterIP") (eq .Values.expose.type "ingress") }}
{{- $clusterIP := .Values.expose.clusterIP }}
  name: {{ include "model.apiGatewayModel" . }}
  labels:
    {{- include "model.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $clusterIP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayModel.tls.enabled }}
      port: {{ default (include "model.apiGatewayModel.httpPort" .) $clusterIP.ports.apiGatewayModelHttp }}
      targetPort: {{ template "model.apiGatewayModel.httpPort" . }}
    - name: stats
      port: {{ default (include "model.apiGatewayModel.statsPort" .) $clusterIP.ports.apiGatewayModelStats }}
      targetPort: {{ template "model.apiGatewayModel.statsPort" . }}
    - name: metrics
      port: {{ default (include "model.apiGatewayModel.metricsPort" .) $clusterIP.ports.apiGatewayModelMetrics }}
      targetPort: {{ template "model.apiGatewayModel.metricsPort" . }}
{{- else if (eq .Values.expose.type "nodePort") }}
{{- $nodePort := .Values.expose.nodePort }}
  name: {{ include "model.apiGatewayModel" . }}
  labels:
    {{- include "model.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $nodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayModel.tls.enabled }}
      port: {{ default (include "model.apiGatewayModel.httpPort" .) $nodePort.ports.apiGatewayModelHttp.port }}
      targetPort: {{ template "model.apiGatewayModel.httpPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayModelHttp.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayModelHttp.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayModelHttp.nodePort }}
      {{- end }}
    - name: stats
      port: {{ default (include "model.apiGatewayModel.statsPort" .) $nodePort.ports.apiGatewayModelStats.port }}
      targetPort: {{ template "model.apiGatewayModel.statsPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayModelStats.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayModelStats.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayModelStats.nodePort }}
      {{- end }}
    - name: metrics
      port: {{ default (include "model.apiGatewayModel.metricsPort" .) $nodePort.ports.apiGatewayModelMetrics.port }}
      targetPort: {{ template "model.apiGatewayModel.metricsPort" . }}
      {{- if and (ge ($nodePort.ports.apiGatewayModelMetrics.nodePort | int) (30000 | int)) (le ($nodePort.ports.apiGatewayModelMetrics.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.apiGatewayModelMetrics.nodePort }}
      {{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
  name: {{ include "model.apiGatewayModel" . }}
  labels:
    {{- include "model.labels" . | indent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with $loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- with $loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $loadBalancer.IP }}
  loadBalancerIP: {{ $loadBalancer.IP }}
  {{- end }}
  ports:
    - name: {{ ternary "https" "http" .Values.apiGatewayModel.tls.enabled }}
      port: {{ default (include "model.apiGatewayModel.httpPort" .) $loadBalancer.ports.apiGatewayModelHttp }}
      targetPort: {{ template "model.apiGatewayModel.httpPort" . }}
    - name: stats
      port: {{ default (include "model.apiGatewayModel.statsPort" .) $loadBalancer.ports.apiGatewayModelStats }}
      targetPort: {{ template "model.apiGatewayModel.statsPort" . }}
    - name: metrics
      port: {{ default (include "model.apiGatewayModel.metricsPort" .) $loadBalancer.ports.apiGatewayModelMetrics }}
      targetPort: {{ template "model.apiGatewayModel.metricsPort" . }}
{{- end }}
  selector:
    {{- include "model.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway-model
