name: Helm Integration Test (latest)

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release-please--branches--main

jobs:
  backend:
    strategy:
      fail-fast: false
      matrix:
        component: [model-backend]
    uses: instill-ai/model/.github/workflows/helm-integration-test-backend.yml@sarthakgupta/update-helm-integration-test-latest-release-workflow
    with:
      component: ${{ matrix.component }}
      target: latest
